spring:
  application:
    name: demo-api
  datasource:
    url: jdbc:postgresql://${DB_HOST:localhost}:${DB_PORT:5432}/${DB_NAME:mydb}
    username: ${DB_USERNAME:user-local}
    password: ${DB_PASSWORD:password}
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    properties:
      hibernate:
        format_sql: true
        show_sql: true
        use_sql_comments: true
        jdbc:
          batch_size: 50
          fetch_size: 50
  flyway:
    locations: classpath:db/migration

jwt:
  secret: ${JWT_SECRET:IdgYppGhxiaJPRCSswyaZ0RBFilMJSxWeo5dMSHfouh12NwYzL9heQsNNjBv0D6WcDjlgHe0GDUs4GMloMkytQ==}
  expiration: ${JWT_EXPIRATION:86400000}
